### PR TITLE
Upgrade/pyjwt support

### PR DESCRIPTION
**Pull request by monkut**
fix update in pyjwt where `jwt.ExpiredSignature` was changed to `jwt.ExpiredSignatureError`.

```
    jwt_payload = token_validator.validate(jwt_token)
  File ".../site-packages/django_cognito_jwt/validator.py", line 68, in validate
    except (jwt.InvalidTokenError, jwt.ExpiredSignature, jwt.DecodeError) as exc:
rest_framework.request.WrappedAttributeError: module 'jwt' has no attribute 'ExpiredSignature'

```

### CODE REVIEW

**Comment by Vektrat** [comment]
I can confirm this is broken, most likely since https://github.com/jpadilla/pyjwt/commit/f690976596bb74221f5a81fc9afffd5609bc4e70 where they dropped deprecation support for the referenced error in this project

I think it'd also be a good idea to lock compatible versions in the requirements list

This PR would fix https://github.com/labd/django-cognito-jwt/issues/34

**Comment by adamantike** [comment]
@mikedebock @mvantellingen, can you please review this change? The workaround in #34 is not an alternative if you want to use a newer version of libraries depending on `pyjwt` (e.g. latest versions of https://github.com/jazzband/djangorestframework-simplejwt require `pyjwt>=2,<3`)

**Comment by MichelML** [comment]
should be closed in favor of https://github.com/labd/django-cognito-jwt/pull/41#issue-1077075772

**Comment by mikedebock** [comment]
As mentioned by @MichelML this will be resolved in the upcoming 0.0.4 release.
